source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'SwiftyOBD' do
    pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git'
    pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '4.0.0'
    pod 'CircleProgressView', :git => 'https://github.com/CardinalNow/iOS-CircleProgressView.git'
    pod 'DZNEmptyDataSet'
    pod 'XCGLogger', '~> 4.0.0'
    pod 'SwiftyJSON'
end

# You may need the following post_install call to fix on Bug on Eureka's implementation since latest Swift Version
post_install do |installer|
    installer.pods_project.targets.each do |target|

        if  target.name == 'Eureka'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
